<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <DefineConstants>$(DefineConstants);ASYNC_API</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Include="asyncApi\**\*.*" />
    <Content Include="asyncApi\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ApiCodeGenerator.OpenApi.Tests\DefaultTemplateFactoryTests.cs" Link="DefaultTemplateFactoryTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="Moq" Version="4.18.2" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.6.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ApiCodeGenerator.AsyncApi/ApiCodeGenerator.AsyncApi.csproj" />
    <ProjectReference Include="../../src/ApiCodeGenerator.Core/ApiCodeGenerator.Core.csproj" />
  </ItemGroup>

  <ItemGroup Label="Fix NJsonSchema">
    <None Include="../../src/ApiCodeGenerator.AsyncApi/bin/$(Configuration)/netstandard2.0/NJsonSchema.dll" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
