<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net8.0;netstandard2.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <!--Параметры пакета в Directory.Build.targets-->
  </PropertyGroup>

  <ItemGroup>
    <None Include="build/*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Properties\testSchema.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\ApiCodeGenerator.Core\bin\$(Configuration)\netstandard2.0\ApiCodeGenerator.Core.dll" Link="ApiCodeGenerator.Core.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\ApiCodeGenerator.OpenApi\bin\$(Configuration)\netstandard2.0\ApiCodeGenerator.OpenApi.dll" CopyToPublishDirectory="Always" />
    <None Include="..\ApiCodeGenerator.AsyncApi\bin\$(Configuration)\netstandard2.0\ApiCodeGenerator.AsyncApi.dll" CopyToPublishDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiCodeGenerator.Abstraction\ApiCodeGenerator.Abstraction.csproj" />
    <ProjectReference Include="..\ApiCodeGenerator.Core\ApiCodeGenerator.Core.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\ApiCodeGenerator.OpenApi\ApiCodeGenerator.OpenApi.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\ApiCodeGenerator.AsyncApi\ApiCodeGenerator.AsyncApi.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup Label="Nswag prerequiries">
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <Import Project="./ApiCodeGenerator.MSBuild.Console.targets" Condition="'$(TargetFramework)' != 'netstandard2.0'" />
  <Import Project="./ApiCodeGenerator.MSBuild.Task.targets" Condition="'$(TargetFramework)' == 'netstandard2.0'" />

</Project>
